#!/usr/bin/env bash
# 
# Release Packer by ems≈spree
# Create a ZIP-archived release package from the PhotoGIMP repository.
# 

# Filename for the ZIP archive, including a package version number.
ZIP_FILENAME="photogimp_3.$(date +'%Y.%m').zip" # example: photogimp_3.26.04.zip

# List of files and directories to include in the ZIP archive.
FILES_TO_INCLUDE=(
	contextrc
	dockrc
	gimprc
	sessionrc
	shortcutsrc
	splashes
	theme.css
	toolrc
)

# Path to the target directory where the ZIP file will be created.
TARGET_DIR="$(dirname "$PWD")"

# Pack and compress files.
create_archive() {
	zip -r "$TARGET_DIR/$ZIP_FILENAME" "${FILES_TO_INCLUDE[@]}" -x .DS_Store || exit 26
}

# Check if files/folder exists and create archive
if [[ -f gimprc ]] && [[ -f shortcutsrc ]]; then
	create_archive
elif [[ -d .config/GIMP/3.0 ]]; then
	cd .config/GIMP/3.0 || exit 41
	if [[ -f gimprc ]] && [[ -f shortcutsrc ]]; then
		create_archive
	else 
		echo "Error. Files not found. Are you in the reops’s root?" >&2
		exit 42
	fi
else
	echo "Error. Files not found. Are you in the reops’s root?" >&2
	exit 40
fi
